//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.16 at 11:49:18 AM IST 
//


package com.mycompany.project;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mycompany.project package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TestngResults_QNAME = new QName("", "testng-results");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mycompany.project
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TestngResultsType }
     * 
     */
    public TestngResultsType createTestngResultsType() {
        return new TestngResultsType();
    }

    /**
     * Create an instance of {@link TestMethodType }
     * 
     */
    public TestMethodType createTestMethodType() {
        return new TestMethodType();
    }

    /**
     * Create an instance of {@link TestType }
     * 
     */
    public TestType createTestType() {
        return new TestType();
    }

    /**
     * Create an instance of {@link SuiteType }
     * 
     */
    public SuiteType createSuiteType() {
        return new SuiteType();
    }

    /**
     * Create an instance of {@link ClassType }
     * 
     */
    public ClassType createClassType() {
        return new ClassType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TestngResultsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "testng-results")
    public JAXBElement<TestngResultsType> createTestngResults(TestngResultsType value) {
        return new JAXBElement<TestngResultsType>(_TestngResults_QNAME, TestngResultsType.class, null, value);
    }

}
